//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string userNickname { get; set; }
        public string userPassword { get; set; }
        public string userFullName { get; set; }
        public string userAddress { get; set; }
        public string userPhone { get; set; }
        public string userMail { get; set; }
        public Nullable<int> userAge { get; set; }
        public int fl_userRole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
